//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(column_name = "BGM_TOKEN", column_type = "Text", nullable)]
    pub bgm_token: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub save_root_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub db_backup_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub le_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub magpie_path: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
